//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//
//       bebopc version:
//           3.2.3
//
//
//       bebopc source:
//           https://github.com/6over3/bebop
//
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
import { BebopView } from "https://esm.sh/bebop"

export const BEBOP_SCHEMA = new Uint8Array([
  3,
  2,
  0,
  0,
  0,
  73,
  116,
  101,
  109,
  0,
  1,
  0,
  0,
  4,
  0,
  0,
  0,
  0,
  1,
  110,
  97,
  109,
  101,
  0,
  245,
  255,
  255,
  255,
  0,
  80,
  108,
  97,
  121,
  101,
  114,
  0,
  1,
  0,
  0,
  17,
  0,
  0,
  0,
  0,
  5,
  105,
  100,
  0,
  251,
  255,
  255,
  255,
  0,
  110,
  97,
  109,
  101,
  0,
  245,
  255,
  255,
  255,
  0,
  105,
  110,
  118,
  101,
  110,
  116,
  111,
  114,
  121,
  0,
  242,
  255,
  255,
  255,
  0,
  0,
  0,
  0,
  0,
  0,
  102,
  111,
  111,
  0,
  245,
  255,
  255,
  255,
  0,
  100,
  101,
  97,
  100,
  0,
  255,
  255,
  255,
  255,
  0,
  0,
  0,
  0,
  0
])

export const Item = /*#__PURE__*/ Object.freeze(
  /*#__PURE__*/ Object.assign(
    // Factory function
    data => {
      return Object.freeze({
        ...data,
        encode() {
          return Item.encode(this)
        }
      })
    }, // Static methods
    {
      encode(record) {
        const view = BebopView.getInstance()
        view.startWriting()
        Item.encodeInto(record, view)
        return view.toArray()
      },

      encodeInto(record, view) {
        view.writeString(record.name)
      },

      decode(buffer) {
        const view = BebopView.getInstance()
        view.startReading(buffer)
        const decoded = Item.readFrom(view)
        return Item(decoded)
      },

      readFrom(view) {
        let field0
        field0 = view.readString()
        return {
          name: field0
        }
      }
    }
  )
)

export const Player = /*#__PURE__*/ Object.freeze(
  /*#__PURE__*/ Object.assign(
    // Factory function
    data => {
      return Object.freeze({
        ...data,
        encode() {
          return Player.encode(this)
        }
      })
    }, // Static methods
    {
      encode(record) {
        const view = BebopView.getInstance()
        view.startWriting()
        Player.encodeInto(record, view)
        return view.toArray()
      },

      encodeInto(record, view) {
        view.writeUint32(record.id)
        view.writeString(record.name)
        {
          const length0 = record.inventory.length
          view.writeUint32(length0)
          for (let i0 = 0; i0 < length0; i0++) {
            Item.encodeInto(record.inventory[i0], view)
          }
        }
        view.writeString(record.foo)
        view.writeByte(Number(record.dead))
      },

      decode(buffer) {
        const view = BebopView.getInstance()
        view.startReading(buffer)
        const decoded = Player.readFrom(view)
        return Player(decoded)
      },

      readFrom(view) {
        let field0
        field0 = view.readUint32()
        let field1
        field1 = view.readString()
        let field2
        {
          const length0 = view.readUint32()
          field2 = []
          for (let i0 = 0; i0 < length0; i0++) {
            let x0
            x0 = Item.readFrom(view)
            field2[i0] = x0
          }
        }
        let field3
        field3 = view.readString()
        let field4
        field4 = !!view.readByte()
        return {
          id: field0,
          name: field1,
          inventory: field2,
          foo: field3,
          dead: field4
        }
      }
    }
  )
)
